### ISSUE TITLE
Fix AreaFilters build break on main

### ISSUE THREAD

**Issue by JSdotNet** [JSdotNet/Backlog#340]
The solution doesn't compile on main: a test asserts against a filter collection that another merged PR removed. Needs deciding whether the test or the state is right.

## Context

`dotnet build Backlog.sln` fails on `main` in the Backlog repository (JSdotNet/Backlog) with two errors, and has since commit 14656ca:

```
tests/Backlog.Desktop.UI.UnitTests/TagFilterTests.cs(382,60): error CS1061: 'TasksDesktopState' does not contain a definition for 'AreaFilters'
tests/Backlog.Desktop.UI.UnitTests/TagFilterTests.cs(383,36): error CS1061: (same)
```

This is a clean-merge semantic conflict: commit ce5e64d ("Trade the area filter for a No repo scope") removed `AreaFilters` from `src/Modules/Tasks/Backlog.Modules.Tasks.UI/TasksDesktopState.cs`, while PR #327 (5ce0796) added assertions against it in `TagFilterTests.cs`. Both PRs were green in isolation; the combination does not compile. Verified present on `origin/main`, not introduced by any worktree branch.

Consequences beyond the compile error: `dotnet test Backlog.sln` aborts at build and runs zero tests, so the whole suite is unverified on main, and `tests/Backlog.Desktop.UI.UnitTests` can only be run from a stale binary ΓÇö which shows 19 further failures in `GlobalPaneMarkupTests`, `SelectorMarkupTests`, `ToolsTableLayoutTests`, and `FilterBarLayoutTests.Only_the_status_chips_collapse` (expects 1 chip group, sees 3 ΓÇö lines up with the same area-filter removal). Those 19 need re-checking against current source once the project compiles again; some may be stale-binary artifacts and some may be real.

The decision needed: whether the area filter was meant to go (delete or rewrite the assertions and reconcile the 19 markup tests) or whether its removal was too broad (restore `AreaFilters` on the state). Read ce5e64d and PR #327 to establish intent before changing either side. Route the change through the orch-bug skill per the repository's CLAUDE.md gate.

---

_Filed automatically from a Claude Code suggested task._

**Comment by JSdotNet** [comment]
Closed as already-fixed after an issue sweep (`jsdotnet-backlog-20260903-1214`), confidence high.

Fixed by commit c910b17ab16ea0a6f2ebf3c0b2b5f704d7dcfa9f "Drop the area-filter assertions main's tag-chip test kept" (2026-09-02 23:09), confirmed an ancestor of origin/main via `git merge-base --is-ancestor`. That commit answers this issue's explicit open question (test vs. state) in favour of the state: it names the same two commits the issue names (ce5e64d/#325 removed AreaFilters, 5ce0796/#328 added the stale assertions), calls #325 the decision, and drops the two AreaFilters assertions plus the area render assertion from tests/Backlog.Desktop.UI.UnitTests/TagFilterTests.cs (8 insertions, 8 deletions; product code untouched). Current-tree corroboration: `grep -rn "AreaFilters"` over all …

Reopen if this is wrong — the sweep judges against `origin/main`, and it does not run the app.
